# Generated by Django 4.1.7 on 2023-03-21 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracker',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='webapp.project'),
        ),
    ]
