# Generated by Django 4.1.7 on 2023-03-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_projectuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectUser',
        ),
    ]
